// web/src/components/dashboard/Heatmap.vue
<template>
  <div id="d3-wrapper">
  </div>
</template>

<script>
import { clearHeatmap, createHeatmap } from "@/utils/heatmap"

export default {
  name: 'Heatmap',
  data: () => {
    return {
      namespace: '',
      heatmapKind: ''
    }
  },
  methods: {
    getData(heatmapKind, namespace) {
      return new Promise((resolve, reject) => {
        const host = this.$host
        var _ns

        clearHeatmap('#d3-wrapper')

        // Axios
        this.$axios.get(host + '/api/agg/v1/heatmap/' + heatmapKind + '/' + namespace)
          .then((resp) => {
            _ns = resp.data.data

            // Data
            let _x = new Set()
            for (const [k] of Object.entries(_ns)) {
              Object.keys(_ns[k]).forEach(it => _x.add(it))
            }
            const xlabels = Array.from(_x)
            const ylabels = Object.keys(_ns)
            const data = ylabels.map(y => xlabels.map(x => _ns[y][x]))

            resolve({ xlabels, ylabels, data })
          })
          .catch((error) => {
            reject(error)
          })
      })
    },
    generateHeatmap(heatmapKind, namespace) {
      this.heatmapKind = heatmapKind
      this.namespace = namespace

      this.getData(heatmapKind, namespace)
        .then(data => {
          createHeatmap('#d3-wrapper', data, this._calcColor, this._breakString)    
        })
        .catch((error) => {
          console.log('[ERROR]', error)
          alert('Unexpected error occurred.')
        })
    },
        _calcColor(verbs) {
      // rgb(39, 100, 25)
      if (verbs == undefined || verbs.length == 0) return '#27641910' // .0

      let verbsSet = new Set(verbs)
      if (verbsSet.has("delete") || verbsSet.has("deletecollection")) {
        return '#276419' // 1.00
      } else if (verbsSet.has("update") || verbsSet.has("create") || verbsSet.has("patch")) {
        return '#276419a8' // .66
      } else if (verbsSet.has("get") || verbsSet.has("list") || verbsSet.has("watch")) {
        return '#27641954' // .33
      } else {
        return '#27641907' // .07
      }
    },
    _breakString(str) {
      const limit = 7
      const _fn = (str, limit) => (str.length <= limit) ? str + '   ' : (str.substr(0, limit) + '...')
      return _fn(str, limit)
    }
  }
}
</script>

<style lang="scss" scoped>
#d3-wrapper {
  width: 100%;
  overflow-x: scroll;
  overflow-y: scroll;

  .ylabel {
    cursor: pointer;
  }
}
</style>

// lens-extension/src/components/heatmap.tsx
/* heatmap 컴포넌트를 반환 */
import React, { useEffect } from "react";
import { clearHeatmap, createHeatmap } from "../api/heatmap";
import { Renderer } from "@k8slens/extensions";

type HeatmapProps = {
  xlabels: Array<string>;
  ylabels: Array<string>;
  data: Array<Array<Array<string>>>;
  loading: boolean;
  addressValidity: boolean;
};
export const Heatmap = (heatmapData: HeatmapProps) => {
  useEffect(() => {
    clear();
    generateHeatmap(heatmapData);
  }, [heatmapData]);

  const generateHeatmap = (heatmapData: HeatmapProps) => {
    createHeatmap("#d3-wrapper", heatmapData, _calcColor, _breakString);
  };
  const clear = () => {
    clearHeatmap("#d3-wrapper");
  };

  const _breakString = (str: string) => {
    const limit = 7;
    const _fn = (st: string, limit: number) =>
      str.length <= limit ? str + "   " : str.substr(0, limit) + "...";
    return _fn(str, limit);
  };

  const _calcColor = (verbs: any) => {
    const colorList = ["#27641907", "#27641954", "#276419a8", "#276419"]; // rgb(39, 100, 25)
    if (verbs == undefined || verbs.length == 0) return colorList[0];
    let verbsSet = new Set(verbs);
    if (verbsSet.has("delete") || verbsSet.has("deletecollection")) {
      return colorList[3];
    } else if (
      verbsSet.has("update") ||
      verbsSet.has("create") ||
      verbsSet.has("patch")
    ) {
      return colorList[2];
    } else if (
      verbsSet.has("get") ||
      verbsSet.has("list") ||
      verbsSet.has("watch")
    ) {
      return colorList[1];
    } else {
      return colorList[0];
    }
  };

  return (
    <>
      {!heatmapData.addressValidity ? (
        <div className="NoItems flex box grow">
          <div className="box center">invalid address</div>
        </div>
      ) : heatmapData.loading ? (
        <Renderer.Component.Spinner center />
      ) : (
        <div className="VirtualList KubeObjectListLayout box grow">
          <div className="List">
            <div id="d3-wrapper" />
          </div>
        </div>
      )}
    </>
  );
};
